### ISSUE TITLE
[BUG] TypeError: undefined is not an object (evaluating '_a[0].comment.map')

### ISSUE THREAD

**Issue by gander** [k-yle/osm-api-js#10]
```js
import { getChangeset } from "osm-api";
console.log(await getChangeset(153287946))
```

```
4364 |         max_lat: +raw.$.max_lat,
4365 |         max_lon: +raw.$.max_lon,
4366 |         uid: +raw.$.uid,
4367 |         user: raw.$.user,
4368 |         tags: Object.fromEntries(raw.tag.map((tag) => [tag.$.k, tag.$.v])),
4369 |         discussion: (_a = raw.discussion) === null || _a === void 0 ? void 0 : _a[0].comment.map((comment) => ({
                                                                                            ^
TypeError: undefined is not an object (evaluating '_a[0].comment.map')
      at mapRawChangeset (/home/gander/PhpstormProjects/untitled/node_modules/osm-api/dist/index.js:4369:86)
      at map (:1:11)
      at /home/gander/PhpstormProjects/untitled/node_modules/osm-api/dist/index.js:4401:37
      at fulfilled (/home/gander/PhpstormProjects/untitled/node_modules/osm-api/dist/index.js:4333:58)

Bun v1.1.17 (Linux x64)
```

```
/home/gander/PhpstormProjects/untitled/node_modules/osm-api/dist/index.js:4369
        discussion: (_a = raw.discussion) === null || _a === void 0 ? void 0 : _a[0].comment.map((comment) => ({
                                                                                             ^

TypeError: Cannot read properties of undefined (reading 'map')
    at mapRawChangeset (/home/gander/PhpstormProjects/untitled/node_modules/osm-api/dist/index.js:4369:94)
    at Array.map (<anonymous>)
    at /home/gander/PhpstormProjects/untitled/node_modules/osm-api/dist/index.js:4401:37
    at Generator.next (<anonymous>)
    at fulfilled (/home/gander/PhpstormProjects/untitled/node_modules/osm-api/dist/index.js:4333:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v22.2.0
```

**Comment by k-yle** [comment]
thanks for raising this issue! I've just released v2.1.2 which fixes the bug.

Not sure what caused this to stop working, but we now have a test case to prevent this from happening again...
